# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 913c9726d46d53857b1f16e2ad7f2dd614e674deb5b39ec8432c48a1653ff2651837d7e608e198103b0aa0331ba8abf8f4d7f9901d3f430dbf55cab60b761d8c

test:
  secret_key_base: 6e816ebc5b347d2016dfefe961a5ce7a51e76ba0ba9fd77fe7e78f4954723dca2ae6f8074829109c50fa2047e47faa98cd86baddd081fd3a1eb70f0d4744ae8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
