# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4c5673e444fa2a819d5b4f37dbbe1f2917dce4c82fb203718c813656a0bbb9c7f6e36f28f155c59c5f3fed4bd32c1f2bc483e1eeb8637cd924680dbd51a4b7

test:
  secret_key_base: bfe48754d1a04361ada21bd5640afad7a9806262130a3a86a331c4f5679d30936fe30d2baaa984b24bf6873ead4a9524050b92a7cf679757cd7cb66b2be9b681

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
