# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f946dbad290dbe5e0681ac927b1296377bd687464a262bd682bccfcae44368257973db1a749334aae39e3f95a2fdd13c3f2dd89bccbdcd1dc25191e3d14fdf3d

test:
  secret_key_base: a718e979f4c4e9fcd6b8e860349457a36719f4ed40c114307fe4b320edb6340def9d76ddf15aa09af57b6774a27abfb481a5f3d438a5f67dfe9ab40a771b1ab9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
