# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68053659d078fd584384961d3b8be3ac64bd7ae133442e88dccfcd714d2de787a78efe5b63b65d09ed50a6d0ed99a4f118266147d4580567218ed21e2f3d62f6

test:
  secret_key_base: 8dcb007833b0a8847c65aa149f556f04416564d0bc68ce141a4120692a77b4c3c14fe494b5fd173549699de855b708b39619c70b9a19a46a32a0fef282843476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
