# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ade6275415f14ff91f6438da8e44b25686be3b6c9c3d41bf753ab488e230f5e19dea9d8be3417848cc64bb1667ffc00928724bb1ae1a3c06ea8af923a9767803

test:
  secret_key_base: b3827dd84ad71c5160741640d50ac99bb7ddf8de69c931aca85d0201804a7c7f79995bedc6923258e478b6d6186171facf3e645ccd056cbc6edc65fc16f19adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
